name: smagnet
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - absl-py=2.1.0=py39h06a4308_0
  - aiohttp=3.9.5=py39h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - arrow-cpp=17.0.0=h865e1df_1
  - async-timeout=4.0.3=py39h06a4308_0
  - aws-c-auth=0.6.19=h5eee18b_0
  - aws-c-cal=0.5.20=hdbd6064_0
  - aws-c-common=0.8.5=h5eee18b_0
  - aws-c-compression=0.2.16=h5eee18b_0
  - aws-c-event-stream=0.2.15=h6a678d5_0
  - aws-c-http=0.6.25=h5eee18b_0
  - aws-c-io=0.13.10=h5eee18b_0
  - aws-c-mqtt=0.7.13=h5eee18b_0
  - aws-c-s3=0.1.51=hdbd6064_0
  - aws-c-sdkutils=0.1.6=h5eee18b_0
  - aws-checksums=0.1.13=h5eee18b_0
  - aws-crt-cpp=0.18.16=h6a678d5_0
  - aws-sdk-cpp=1.11.212=hecad206_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - blinker=1.6.2=py39h06a4308_0
  - boost-cpp=1.82.0=hdb19cb5_2
  - bottleneck=1.3.7=py39ha9d4c09_0
  - brotli=1.0.9=h5eee18b_8
  - brotli-bin=1.0.9=h5eee18b_8
  - brotli-python=1.0.9=py39h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.11.26=h06a4308_0
  - cachetools=5.3.3=py39h06a4308_0
  - certifi=2024.12.14=py39h06a4308_0
  - cffi=1.16.0=py39h5eee18b_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=py39h06a4308_0
  - contourpy=1.2.0=py39hdb19cb5_0
  - cryptography=42.0.5=py39hdda0065_1
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dbus=1.13.18=hb2f20db_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - dill=0.3.8=py39h06a4308_0
  - expat=2.6.2=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py39h06a4308_0
  - fontconfig=2.14.1=h4c34cd2_2
  - fonttools=4.51.0=py39h5eee18b_0
  - freetype=2.12.1=h4a9f257_0
  - frozenlist=1.4.0=py39h5eee18b_0
  - fsspec=2024.3.1=py39h06a4308_0
  - gflags=2.2.2=h6a678d5_1
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - glog=0.5.0=h6a678d5_1
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py39heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - google-auth=2.29.0=py39h06a4308_0
  - google-auth-oauthlib=0.5.2=py39h06a4308_0
  - grpcio=1.62.2=py39h6a678d5_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - gtest=1.14.0=hdb19cb5_0
  - huggingface_hub=0.24.6=py39h06a4308_0
  - icu=73.1=h6a678d5_0
  - idna=3.7=py39h06a4308_0
  - importlib_metadata=7.0.1=hd3eb1b0_0
  - importlib_resources=6.1.1=py39h06a4308_1
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.3=py39h06a4308_0
  - joblib=1.4.0=py39h06a4308_0
  - jpeg=9e=h5eee18b_1
  - jupyter_client=8.6.0=py39h06a4308_0
  - jupyter_core=5.5.0=py39h06a4308_0
  - kiwisolver=1.4.4=py39h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libboost=1.82.0=h109eef0_2
  - libbrotlicommon=1.0.9=h5eee18b_8
  - libbrotlidec=1.0.9=h5eee18b_8
  - libbrotlienc=1.0.9=h5eee18b_8
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.9.1.3=0
  - libcups=2.4.2=h2d74bed_1
  - libcurand=10.3.5.147=0
  - libcurl=8.11.1=hc9e6f67_0
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=11.2.0=h1234567_1
  - libgrpc=1.62.2=h2d74bed_0
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libllvm14=14.0.6=hdb19cb5_3
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=11.7.4.75=0
  - libnvjpeg=11.8.0.2=0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.17=hdbd6064_0
  - libprotobuf=4.25.3=he621ea3_0
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libthrift=0.15.0=h1795dd8_2
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h5eee18b_1
  - libxml2=2.10.4=hfdd30dd_2
  - lz4-c=1.9.4=h6a678d5_1
  - markdown=3.4.1=py39h06a4308_0
  - markupsafe=2.1.3=py39h5eee18b_0
  - matplotlib=3.8.4=py39h06a4308_0
  - matplotlib-base=3.8.4=py39h1128e8f_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py39h5eee18b_1
  - mkl_fft=1.3.8=py39h5eee18b_0
  - mkl_random=1.2.4=py39hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py39h06a4308_0
  - multidict=6.0.4=py39h5eee18b_0
  - mysql=5.7.24=h721c034_2
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py39h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py39h06a4308_0
  - numexpr=2.8.7=py39h85018f9_0
  - numpy=1.26.4=py39h5f9d8c6_0
  - numpy-base=1.26.4=py39hb5e798b_0
  - oauthlib=3.2.2=py39h06a4308_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.15=h5eee18b_0
  - orc=2.0.1=h2d29ad5_0
  - pandas=2.2.1=py39h6a678d5_0
  - pcre2=10.42=hebb0a14_1
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=10.3.0=py39h5eee18b_0
  - pip=24.0=py39h06a4308_0
  - ply=3.11=py39h06a4308_0
  - prompt-toolkit=3.0.43=py39h06a4308_0
  - protobuf=4.25.3=py39h12ddb61_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pyjwt=2.8.0=py39h06a4308_0
  - pyopenssl=24.0.0=py39h06a4308_0
  - pyparsing=3.0.9=py39h06a4308_0
  - pyqt=5.15.10=py39h6a678d5_0
  - pyqt5-sip=12.13.0=py39h5eee18b_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.19=h955ad1f_1
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python-xxhash=2.0.2=py39h5eee18b_1
  - pytorch=2.0.1=py3.9_cuda11.7_cudnn8.5.0_0
  - pytorch-cuda=11.7=h778d358_5
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=py39h06a4308_0
  - qt-main=5.15.2=h53bd1ea_10
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - s2n=1.3.27=hdbd6064_0
  - scikit-learn=1.4.2=py39h1128e8f_1
  - scipy=1.11.4=py39h5f9d8c6_0
  - setuptools=69.5.1=py39h06a4308_0
  - sip=6.7.12=py39h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.2.1=h6a678d5_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sympy=1.12=py39h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tensorboard=2.12.1=py39h06a4308_0
  - tensorboard-data-server=0.7.0=py39h52d8a92_0
  - tensorboard-plugin-wit=1.8.1=py39h06a4308_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.14=h39e8969_0
  - tomli=2.0.1=py39h06a4308_0
  - torchaudio=2.0.2=py39_cu117
  - torchtriton=2.0.0=py39
  - torchvision=0.15.2=py39_cu117
  - typing-extensions=4.11.0=py39h06a4308_0
  - typing_extensions=4.11.0=py39h06a4308_0
  - tzdata=2024a=h04d1e81_0
  - unicodedata2=15.1.0=py39h5eee18b_0
  - urllib3=2.1.0=py39h06a4308_1
  - utf8proc=2.6.1=h5eee18b_1
  - werkzeug=2.3.8=py39h06a4308_0
  - wheel=0.43.0=py39h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.9.3=py39h5eee18b_0
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.5=hc292b87_2
  - pip:
      - affine==2.4.0
      - anyio==4.3.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - argparse==1.4.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - attrs==23.2.0
      - autograd==1.7.0
      - babel==2.15.0
      - batchgenerators==0.25.1
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - click-plugins==1.1.1
      - cligj==0.7.2
      - cloudpickle==3.1.1
      - comm==0.2.2
      - contextlib2==21.6.0
      - datasets==3.2.0
      - debugpy==1.8.1
      - defusedxml==0.7.1
      - efficientnet-pytorch==0.7.1
      - exceptiongroup==1.2.1
      - executing==2.0.1
      - fastjsonschema==2.19.1
      - fqdn==1.5.1
      - future==1.0.0
      - gdown==5.2.0
      - geopandas==1.0.1
      - h11==0.14.0
      - h5py==3.12.1
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-hub==0.27.0
      - imagecodecs==2024.1.1
      - imageio==2.36.0
      - importlib-metadata==7.1.0
      - ipykernel==6.29.4
      - ipython==8.18.1
      - ipywidgets==8.1.2
      - isoduration==20.11.0
      - jedi==0.19.1
      - json5==0.9.25
      - jsonpointer==2.4
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyter==1.0.0
      - jupyter-client==8.6.1
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.1.8
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.1
      - jupyterlab-widgets==3.0.10
      - lazy-loader==0.4
      - linecache2==1.0.0
      - llvmlite==0.43.0
      - matplotlib-inline==0.1.7
      - mistune==3.0.2
      - ml-collections==0.1.1
      - multiprocess==0.70.16
      - munch==4.0.0
      - narwhals==1.25.1
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - notebook==7.1.3
      - notebook-shim==0.2.4
      - numba==0.60.0
      - opencv-python==4.9.0.80
      - overrides==7.7.0
      - packaging==24.0
      - pandoc==2.4
      - pandocfilters==1.5.1
      - parso==0.8.4
      - patsy==1.0.1
      - pexpect==4.9.0
      - platformdirs==4.2.1
      - plotly==6.0.0
      - plumbum==1.9.0
      - pretrainedmodels==0.7.4
      - progressbar2==4.5.0
      - prometheus-client==0.20.0
      - psutil==5.9.8
      - pyarrow==18.1.0
      - pycparser==2.22
      - pygam==0.9.1
      - pygments==2.18.0
      - pyogrio==0.11.1
      - pyproj==3.6.1
      - python-dateutil==2.9.0.post0
      - python-json-logger==2.0.7
      - python-utils==3.9.1
      - pyyaml==6.0.1
      - pyzmq==26.0.3
      - qtconsole==5.5.2
      - qtpy==2.4.1
      - rarfile==4.2
      - rasterio==1.3.10
      - referencing==0.35.1
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.18.1
      - safetensors==0.4.3
      - scikit-image==0.24.0
      - seaborn==0.13.2
      - segmentation-models-pytorch==0.5.0
      - send2trash==1.8.3
      - shap==0.46.0
      - shapely==2.0.7
      - slicer==0.0.8
      - sniffio==1.3.1
      - snuggs==1.4.7
      - soupsieve==2.5
      - stack-data==0.6.3
      - statsmodels==0.14.4
      - terminado==0.18.1
      - tifffile==2024.5.10
      - timm==0.9.2
      - tinycss2==1.3.0
      - tornado==6.4
      - tqdm==4.66.4
      - traceback2==1.4.0
      - traitlets==5.14.3
      - types-python-dateutil==2.9.0.20240316
      - unittest2==1.1.0
      - uri-template==1.3.0
      - wcwidth==0.2.13
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.10
      - xxhash==3.5.0
      - zipp==3.18.1
